### ISSUE TITLE
Making Floki support XML files parsing.

### ISSUE THREAD

**Issue by oswaldoferreira** [philss/floki#13]
I'm getting this error when parsing a XML file.

`** (MatchError) no match of right hand side value: {"version", "1.0"}`

Removing this line:

`<?xml version="1.0" encoding="UTF-8"?>`

From:

```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title></title>
    <link></link>
    <description></description>
    <language></language>
    <copyright></copyright>
    <lastBuildDate></lastBuildDate>
    <docs></docs>
    <image>
      <url></url>
      <title></title>
      <link></link>
      <width></width>
      <height></height>
      <description>
      </description>
    </image>
    <item>
      <title></title>
      <link></link>
      <description></description>
      <category></category>
      <pubDate></pubDate>
    </item>
    <item>
      <title></title>
      <link></link>
      <description></description>
      <category></category>
      <pubDate></pubDate>
    </item>
  </channel>
</rss>
```
It seems to work just fine. 

Any thought's on supporting this kind of file?

**Comment by philss** [comment]
Hi @oswaldoferreira, great to know that you are using Floki!

I didn't think in using Floki to parse and search XML files, but seems to be a good idea.
In my first try I could parse/find nodes only by ignoring the line that you mentioned.

Do you think there is some case this information is needed?

**Comment by philss** [comment]
@oswaldoferreira I just released a version with that improvement. It's version `0.3.1`. Please update and take a look.

I'm closing this issue. Fell free to re-open in case it doesn't work.

**Comment by oswaldoferreira** [comment]
Great! Thanks @philss. I'm going to try this now.
