### ISSUE TITLE
raw_html removes content within self closing tags

### ISSUE THREAD

**Issue by navinpeiris** [philss/floki#132]
When using `raw_html` with self closing tags that contain some text, the said text is lost in the output. This becomes problematic when trying to get the xml content for rss items etc.

For example, using `raw_html` after parsing the following xml:

```xml
<item>
  <link>www.example.com</link>
</item>
```

results in:

```xml
<item>
  <link/></link>
</item>

**Comment by navinpeiris** [comment]
Pull requested submitted for this issue: https://github.com/philss/floki/pull/131

**Comment by mischov** [comment]
In HTML5 void elements (which `<link>` is) cannot have closing tags, and consequently cannot have contents. https://html.spec.whatwg.org/multipage/syntax.html#elements-2.

I believe void elements should get closed automatically by HTML5 parsers, meaning that if they have contents, it will be parsed as the contents of the void element's parent. 

In your case, this means that the correct HTML5 parsing of

```html
<item>
  <link>www.example.com</link>
</item>
```
would be

```html
<item>
  <link /> www.example.com
</item>
```
As you say, this causes problems when trying to parse XML, but at the moment Floki  [only supports HTML](https://github.com/philss/floki/issues/94#issuecomment-283547635).

**Comment by mischov** [comment]
That said, your fix suggests that the data is being incorrectly parsed by `mochiweb_html`, then just dropped by `raw_html`, so maybe your fix is a good one for this particular case.

**Comment by philss** [comment]
Yes, I'm assuming that his fix is meant to represent HTML that was wrongly parsed. I think it's OK to support this scenario, even if it's representing an "invalid" HTML5 since it is what was the parsed tree.

Thank you @navinpeiris and @mischov! 😃
