### ISSUE TITLE
Get values using multiple selectors

### ISSUE THREAD

**Issue by caalberts** [philss/floki#134]
I'm working on parsing a HTML listing to get various attributes from each listing.

An example of what I'm doing:

Given the following HTML:
```
<div class="container">
  <div class="item">
    <h3>Item 1</h3>
    <p>item 1 description</p>
  </div>
  <div class="item">
    <h3>Item 2</h3>
    <p>item 2 description</p>
  </div>
</div>
```

I'd like to get a list of item names and descriptions:
```
[
  {name: "Item 1", description: "Item 1 description"}
  {name: "Item 2", description: "Item 2 description"}
]
```

My current approach:
```
  defp get_products(html) do
    html
    |> Floki.find(".item")
    |> Enum.map(&parse_product/1)
  end

  defp parse_product(item) do
    name = item |> Floki.find("h3") |> Floki.text
    description = item |> Floki.find("p") |> Floki.text

    %{name: name, description: description}
  end
```

Is there a better approach to getting the name and description without using multiple `Floki.find` calls?

**Comment by mischov** [comment]
That's how I'd do it.

There is some duplicate overhead for running `Floki.find` multiple times on the same item because `Floki.find` has to convert the item to an `HTMLTree` in both finds, but generally the items selected as part of this pattern are pretty small and the overhead is low.

I actually designed [Meeseeks](https://github.com/mischov/meeseeks) a bit differently than Floki with this "select data from a list of items" use case in mind [(see the History section here)](https://github.com/mischov/meeseeks/issues/2), and avoid some of this work, but the performance isn't *that much* different [(see this benchmark)](https://github.com/mischov/meeseeks_floki_bench#the-trending-js-benchmark).

**Comment by philss** [comment]
Today there is no better way of doing that. I think an implementation of `Floki.text/1` that returns a list of text nodes would make things easier.

For example:

```elixir
defp parse_product(item) do
  [name, description] = Floki.text_nodes(item)

  %{name: name, description: description}
end
```

What do you think? It would help?

**Comment by mischov** [comment]
I know that a lot of times when I'm trying to parse an item from a list of items I'm also getting an `href` attribute, or something nested down further.

Something like `text_nodes` might help in some cases, but I think @caalberts's current approach is the clearest, most flexible solution.

**Comment by philss** [comment]
@mischov yes, you are right about being the most flexible. I think the `text_nodes` would help in this and other cases, but not necessarily is the clearest way. 

@caalberts there is another way to do that without a new function. You could find the inner elements using `Floki.find("h3, p")`. This will only work if the only nodes inside the `.item` are "h3" and "p".

Example:

```elixir
html
|> Floki.find(".item")
|> Enum.map(fn(item) -> Floki.find(item, "h3, p") end)
|> Enum.map(fn([{"h3", _, [item]}, {"p", _, [desc]}]) ->
  %{name: item, description: desc}
end)
```

You could improve the pattern matching to make it work in other cases too.

Another way is to use only one "find". Like this:

```elixir
html
|> Floki.find(".item h3, .item p")
|> Enum.chunk_every(2)
|> Enum.map(fn([{"h3", _, [item]}, {"p", _, [desc]}]) ->
  %{name: item, description: desc}
end)
```

Again, you have the same limitation of the previous version.

**Comment by caalberts** [comment]
Thanks for the suggestions.

@philss `text_nodes` is a good idea, but I think it might get unwieldy when the element has many nested elements. If a user is only interested in a few of the text nodes, pattern matching for the required text nodes would be very cumbersome.

**Comment by philss** [comment]
@caalberts OK, thanks for the advice! I think I will put aside that idea for a bit.

May I close this issue for now?

**Comment by caalberts** [comment]
:+1:

**Comment by caalberts** [comment]
Just to follow up, after trying out

```
html
|> Floki.find(".item h3, .item p")
|> Enum.chunk_every(2)
|> Enum.map(fn([{"h3", _, [item]}, {"p", _, [desc]}]) ->
  %{name: item, description: desc}
end)
```

The pattern match would raise error when the element becomes more complex. For example, an element like `<h3><a href="#">Product <span>name</span></a></h3>`, would return a longer list that would not match `[item]`. The pattern matching needs to be very precise and it makes the implementation very rigid.

I'll stick with my previous approach. Thanks so much for the suggestions. 😄
