### ISSUE TITLE
Add complex selections to `:nth-child` pseudo-class selector

### ISSUE THREAD

**Issue by philss** [philss/floki#145]
Today we only accept simple selectors, like `:nth-child(1)`, `:nth-child(odd)` or `:nth-child(even)`.

The idea is to support more complex selectors, like: `:nth-child(2n+1)`.

Examples can be found here: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

**Comment by mischov** [comment]
The regex for parsing functional notation arguments does not appear to account for whitespace.

```elixir
iex(1)> r = ~r/^(?<a>[-+]?[0-9]*[n])\+?(?<b>[0-9]*)$/
~r/^(?<a>[-+]?[0-9]*[n])\+?(?<b>[0-9]*)$/

iex(2)> Regex.named_captures(r, "-n+6")
%{"a" => "-n", "b" => "6"}

iex(3)> Regex.named_captures(r, "-n+ 6")
nil
```

See: https://drafts.csswg.org/selectors-3/#nth-child-pseudo

**Comment by mischov** [comment]
@philss @nirev 
Support for a negative `b` value also appears to be missing.

From above document: `:nth-child(10n-1)  /* represents the 9th, 19th, 29th, etc, element */`

```elixir
Regex.named_captures(r, "10n-1") 
nil
```

**Comment by nirev** [comment]
Thanks, @mischov!

I'll fix those!

**Comment by philss** [comment]
Thank you, @mischov and @nirev!
