### ISSUE TITLE
deep_text fails when handling comments

### ISSUE THREAD

**Issue by gverilla** [philss/floki#15]
When I try to extract text from elements containing a comment-tag, the deep_text-extraction breaks. Instead of ignoring the comment, it throws a FunctionClauseError.

Here is a minimal example:

    defmodule FlokiCase do
      def fail_deep_text_with_comment do
        """
        <a>foo</a>
        
        <b>baz</b>
        """ |> Floki.parse |> Floki.text |> IO.puts
      end
    end

I expected to have it returned "foobaz", but instead got this [error output](http://pastebin.com/GkbUi0Dx).
I hope this helps.

**Comment by philss** [comment]
@gverilla Thanks for the report! :smiley: I fixed it in version `0.3.2`. Please check this new version.

I'm closing this issue now.
