### ISSUE TITLE
raw_html does not re-encode HTML entities

### ISSUE THREAD

**Issue by pguillory** [philss/floki#158]
Example:
```elixir
iex(1)> Floki.parse("<span>&lt;video&gt;</span>") |> Floki.raw_html
"<span><video></span>"
```
Expected:
```elixir
"<span>&lt;video&gt;</span>"
```

**Comment by philss** [comment]
Hi, @pguillory ! Sorry for the delay. This is a good point.

This PR should solve the problem: https://github.com/philss/floki/pull/159. Can you check, please?
Thanks!

**Comment by pguillory** [comment]
Thanks for the fix!
