### ISSUE TITLE
HtmlEntities module not found for encode/1 when running production

### ISSUE THREAD

**Issue by kevinwo** [philss/floki#163]
When `defp raw_html([string | tail], html) when is_binary(string)` attempts to use HtmlEntities.encode/1, it cannot be found:

> ** (exit) an exception was raised:
    ** (UndefinedFunctionError) function HtmlEntities.encode/1 is undefined (module HtmlEntities is not available)
        HtmlEntities.encode("Text")
        (floki) lib/floki.ex:114: Floki.raw_html/2
        (floki) lib/floki.ex:157: Floki.tag_for/3
        (floki) lib/floki.ex:136: Floki.raw_html/2
        (floki) lib/floki.ex:157: Floki.tag_for/3
        (floki) lib/floki.ex:136: Floki.raw_html/2
        (floki) lib/floki.ex:158: Floki.tag_for/3
        (floki) lib/floki.ex:136: Floki.raw_html/2

Things run just fine locally on dev, but seem to run into the above issue on production deployment.

**Comment by philss** [comment]
Hi @kevinwo! The PR #165 should fix the problem. I will release a new version very soon. Thanks!

**Comment by philss** [comment]
@kevinwo please try again with version `0.19.3`. It should work now.
