### ISSUE TITLE
Proposal: add parser adapter using myhtmlex

### ISSUE THREAD

**Issue by f34nk** [philss/floki#171]
> Myhtmlex
A module to decode html into a tree structure.
Based on Alexander Borisov’s myhtml, this binding gains the properties of being html-spec compliant and very fast.

see [@Overbryd comment](https://github.com/philss/floki/issues/37#issuecomment-367363433)
>I also wrote https://github.com/Overbryd/nodex that can be used to provide a safe execution (c-)node to give the best in performance/safety.
I would refrain from using myhtmlex widely as a NIF without explicitly checking the crash-safety requirements of the application requiring it. So maybe providing two modes of operation (NIF and C-Node) might be the best way to go for a widely used package.

see myhtmlex branch: [c-node](https://github.com/Overbryd/myhtmlex/tree/c-node)

**Comment by alex88** [comment]
Is there an update on this or any way to speed up the use of `find` and parsing? Trying to profile our app we're seeing that mochiweb_html functions are those taking most of the time

**Comment by philss** [comment]
@f34nk @alex88 thanks to @rinpatch (https://github.com/philss/floki/pull/240), we now can use `myhtmlex` through [`fast_html`](https://hexdocs.pm/fast_html/readme.html).

Please try the version from master/GitHub. I'm going to release this with the version `0.24`.
