### ISSUE TITLE
Selectors that include semicolons are treated as pseudo class selectors

### ISSUE THREAD

**Issue by merongivian** [philss/floki#172]
First of all thanks for the awesome library, works great for parsing xml

Im trying to use find for getting a node that a has a semicolon, in this example i want to get `yt:channelId`

```xml
<feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/" xmlns="http://www.w3.org/2005/Atom">
  <link rel="self" href="http://www.youtube.com/feeds/videos.xml?user=google"/>
  <id>yt:channel:UCK8sQmJBp8GCxrOtXWBpyEA</id>
  <yt:channelId>UCK8sQmJBp8GCxrOtXWBpyEA</yt:channelId>
  <title>Google</title>
</feed>
```

But when i try i `Floki.find("yt:channelid")` i get:
`[warn]  Pseudo-class "channelid" is not implemented. Ignoring`

Is there a way to ignore the colon, so it doesn't think its a pseudo class selector?

**Comment by mischov** [comment]
Try `Floki.find(xml, "channelid")`.

**Comment by merongivian** [comment]
@mischov using the `|` instead of the colon worked, thanks 👍
