### ISSUE TITLE
protocol Enumerable not implemented for "xml"

### ISSUE THREAD

**Issue by mikob** [philss/floki#174]
Seems to be similar to #138 

This is the url I'm trying to parse:
http://t2.jiji.com/linkbox?userID=shinsei-bk_v2&pageID=LB0113_MARKET_COMPOSITE&tab=1

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]                                                                                                                                                                  
Elixir 1.6.1 (compiled with OTP 19) 

Let me know if I can do anything else to help!

**Comment by philss** [comment]
Closing. Please re-open if you still facing the problem in the last version (0.20.1).
