### ISSUE TITLE
Floki.find/2 fails on HTML that consists entirely of a comment

### ISSUE THREAD

**Issue by ShaneWilton** [philss/floki#175]
When attempting to upgrade from Floki 0.7.1 to 0.20.0 I noticed this change.

Under 0.7.1:

```
iex(1)> Floki.find("<!-- test -->", "test")
[]
```

Under 0.20.0:

```
iex(1)> Floki.find("<!-- test -->", "test")
** (FunctionClauseError) no function clause matching in Floki.HTMLTree.build/1    
    
    The following arguments were given to Floki.HTMLTree.build/1:
    
        # 1
        {:comment, " test "}
    
    Attempted function clauses (showing 2 out of 2):
    
        def build({tag, attrs, children})
        def build(html_tuples) when is_list(html_tuples)
    
    (floki) lib/floki/html_tree.ex:14: Floki.HTMLTree.build/1
    (floki) lib/floki/finder.ex:47: Floki.Finder.find_selectors/2
    (floki) lib/floki.ex:127: Floki.find/2

```

**Comment by philss** [comment]
@ShaneWilton thank you for the report! This is a bug introduced when we added the `Floki.HTMLTree` abstraction. I will investigate more of this one later.

**Comment by philss** [comment]
@ShaneWilton fixed in [version 0.20.1](https://github.com/philss/floki/blob/master/CHANGELOG.md#0201---2018-04-05). Please check. Thanks!

**Comment by ShaneWilton** [comment]
Thanks Philip!

I'll verify this is fixed when I'm back in my office tomorrow.

**Comment by ShaneWilton** [comment]
@philss I just ran through a battery of tests in my app with 0.20.1, and everything seems to be working great. Thanks for looking into this and fixing the issue!
