### ISSUE TITLE
:last-of-type not working?

### ISSUE THREAD

**Issue by fcastellanos** [philss/floki#177]
I have several elements with the same class and want to select the last one, I'm no CSS expert but according to this [stackoverflow](https://stackoverflow.com/a/7298062/83245) response there's a way by doing this `.myclass:last-of-type` but it seems that Floki does not support it.

When I do this:
```
response.body
|> Floki.find('.mspace:last-of-type')
```

I'm getting this error
```
** (ArgumentError) argument error
    :erlang.apply(46, :id, [])
    (floki) lib/floki/selector.ex:21: Floki.Selector.match?/2
    (floki) lib/floki/finder.ex:77: Floki.Finder.traverse/4
    (floki) lib/floki/finder.ex:73: Floki.Finder.traverse/4
    (floki) lib/floki/finder.ex:47: Floki.Finder.find_selectors/2
    (crossing) lib/scraper.ex:21: Scraper.get_locations/0
```
So in order to get around this at the moment I'm having to do this
```
response.body
|> Floki.find('.mspace')
|> List.last
```

Maybe I'm doing something wrong? 

Thank you so much for this project :)

**Comment by philss** [comment]
Hi, @fcastellanos! Thank you for the report!
Theoretically you are doing right: the syntax `.mspace:last-of-type` is correct. Floki should be able to parse and select the correct nodes. I think this is related somehow to XML namespaces.

Could you provide an example of the document you are having this issue? Thank you! :)

**Comment by fcastellanos** [comment]
This is the link https://apps.cbp.gov/bwt/mobile.asp?action=n&pn=2504

And the example is something like...
```
<div>
  <nav>
    <div class="mspace">
    </div>
  </nav>
  <nav>
    <div class="mspace">
    </div>
  </nav>
</div>
```

I want to grab the last of the `mspace` or the second one which is the same.

**Comment by philss** [comment]
hi @fcastellanos ! sorry for the delay.

I'm not sure what you were doing wrong, but to archive what you want you will need to select first the container that is the parent of the last `.mspace`, and then you select the `.mspace:last-of-type`.
If your last `.mspace` is always inside the last `nav`, you can do the following:

```elixir
Floki.find(html, "nav:last-of-type .mspace:last-of-type")
```

If it's the only one inside the parent, you can omit the `:last-of-type` pseudo-class from `.mspace`.

**Comment by philss** [comment]
Hi @fcastellanos . I will close this one. Feel free to re-open if your problem persist. Thanks!
