### ISSUE TITLE
Remove support for Elixir 1.3 and add support for Elixir 1.7

### ISSUE THREAD

**Issue by philss** [philss/floki#190]
Since we have Elixir 1.7 as the stable version, we can remove support for minor versions that are too old.

This change involves:
- changing the Elixir version requirement at `mix.exs`;
- changing the build matrix on `.travis.yml`.

**Comment by herbstrith** [comment]
Hey there, i made a PR for this issue and i hope it is of your liking.
Also, i have one question: I see that you exclude the elixir 1.6 and the OTP  19.3 combination. Any reason for that? (from what i read on the documentation the two should be compatible)
cheers

**Comment by philss** [comment]
@herbstrith I don't remember any reason for that. Feel free to open another PR with that. Thanks!
