### ISSUE TITLE
Run the formatter on build

### ISSUE THREAD

**Issue by philss** [philss/floki#191]
We should make the formatter run on each build, by using the `--check-formatted` flag.
This change will ensure that each pull request will fail if have formatting issues.

Examples:
- https://github.com/elixir-lang/flow/blob/master/.travis.yml#L24
- https://github.com/elixir-lang/gen_stage/blob/master/.travis.yml#L13

Notice that the [`formatter`](https://medium.com/blackode/code-formatter-the-big-feature-in-elixir-v1-6-0-f6572061a4ba) was introduced in Elixir 1.6. Therefore, we don't need to run it for versions lower than that.

**Comment by hlhr** [comment]
I will submit a PR for this :)

**Comment by hlhr** [comment]
I will submit a PR for this.

**Comment by philss** [comment]
Closed by #195.
