### ISSUE TITLE
How to extract data inside script tag

### ISSUE THREAD

**Issue by navyad** [philss/floki#199]
I have this raw [html][1] which need to be  parsed.

The list of movies lies inside a javascript [tag][3], which is very difficult to parse.

I guess it would be easier if complete DOM tree can be created/loaded and then parse it.

Is there any way to make things easier ?

  [1]: https://gist.github.com/navyad/cd03bc702ea17623571bb89e183f08a8
  [2]: https://github.com/philss/floki
  [3]: https://gist.github.com/navyad/cd03bc702ea17623571bb89e183f08a8#file-imdb_page-L1036

**Comment by mischov** [comment]
If you want to have JS be evaluated you need to fetch the page with a headless browser, which can be done via something like [Hound](https://github.com/HashNuke/hound) or [Wallaby](https://github.com/keathley/wallaby).

If you want to try extracting from that script tag you linked to, you'll need to select the text from that script tag (check out the options for `Floki.text`), the use something like a Regex to select the part you want and, assuming it is json, parse it with something that parses json.

**Comment by navyad** [comment]
Thanks @mischov
