### ISSUE TITLE
Add a more robust representation of selectors

### ISSUE THREAD

**Issue by philss** [philss/floki#20]
The current implementation does not allow searching for elements using a multi selector, like `a.some-class` or `.some-class.another-class`. This is because it is coupled to the idea of one search per selector at time. This means that I can't search a "tag" and a "class" in the same element at the same time.

We need to provide a basic infrastructure to be able to search using groups of selectors.
This could bring a huge flexibility to Floki, since it's would be possible to truly simulates the "jQuery" selector (actually simulates [Sizzle](http://sizzlejs.com/), the jQuery query selector engine).

Examples of queries to support:

- [x] `Floki.find("a.foo")`
- [x] `Floki.find(".foo.bar")`
- [x] `Floki.find(".foo[data-js=bar]")`
- [x] `Floki.find("a.foo[data='baz.html']")`
- [x] `Floki.find("a b.foo")`

The following examples can be implemented as well, but since depends on a more robust representation of the HTML tree, it should be implemented in the future:

- `Floki.find("a + b")` (matches `b` followed by `a`)
- `Floki.find("a > b")` (matches `b` that is right in the first level of children of `a`)
- `Floki.find("a:first-child") (matches `a` when `a` is the first child of its parent)

This issue is related to https://github.com/philss/floki/issues/18

**Comment by edmz** [comment]
Just curious, in you experience, is `Floki.find("a + b")` harder to implement than `Floki.find("a.foo")`?

**Comment by philss** [comment]
@edmz I think it's harder because for the `Floki.find("a + b")` we need to have the concept of "parent" selector, and a "parent lookup". Today it's possible to perform a descending search using `Floki.find("a b")`, but this is easier because we only lookup elements inside the previous selector.

`Floki.find("a.foo")` would require a multiple match in the same element, making it easier than the previous example since we don't need to check the "position", or parent/child element, of the target element inside the HTML tree.

**Comment by philss** [comment]
Just to let you know: I'm working on this. It's getting shape and I should have a working version soon.

**Comment by philss** [comment]
The merge of #22 closes this issue. I will open new issues related to the selectors that are missing.
