### ISSUE TITLE
Floki.raw_html/2 doesn't correctly encode attributes with both single and double quotes

### ISSUE THREAD

**Issue by ericlathrop** [philss/floki#209]
Example:

```elixir
iex(21)> "<span data-stuff=\"&quot;&#39;\">" |> Floki.parse |> Floki.raw_html  
"<span data-stuff='\"''></span>"
```

Expected either:
```elixir
"<span data-stuff='\"&#39;'></span>"
```
or
```elixir
"<span data-stuff=\"&quot;'\"></span>"
```

**Comment by philss** [comment]
@ericlathrop sorry for the delay. Thank you for open it. I believe this can be fixed almost in the same way that was in [Meeseeks](https://github.com/mischov/meeseeks/pull/64).

**Comment by danhuynhdev** [comment]
Hi @ericlathrop, I've created a PR (#227) for this. Hope to get some feedback from you.

**Comment by philss** [comment]
@danhuynhdev Thank you! :purple_heart: 

I'm going to take a look this week, I hope. It looks like it fixes the problem, but I want to check some scenarios.
