### ISSUE TITLE
Replace Travis CI with GitHub actions

### ISSUE THREAD

**Issue by philss** [philss/floki#228]
GitHub Actions is a powerful tool, and seems to be more integrated with GitHub. I think it would be great to give a try and replace our Travis CI setup with a GitHub workflow.

I'm not sure if one can run the tests in her/his fork.

Docs about:
- [About GitHub Actions](https://help.github.com/en/articles/about-github-actions)
- [The Elixir action](https://github.com/actions/setup-elixir) - the Matrix example on README is similar to what we want.

**Comment by donaldducky** [comment]
Hi there, I'm interested in tackling this issue!

**Comment by donaldducky** [comment]
Been trying this out a bit and the action at: https://github.com/actions/setup-elixir is installing erlang/otp using the base version but not accounting for patch versions.

I'll poke around some more later!

That action also downloads/installs the versions, maybe it might be better to point to pre-baked elixir images on dockerhub. Either way, once it's working it can be optimized.
