### ISSUE TITLE
Compilation error: "attribute 'dialyzer' after function definitions"

### ISSUE THREAD

**Issue by henrik** [philss/floki#24]
I get this trying to `mix deps.compile floki` on my OS X machine:

```
/usr/local/Cellar/erlang/18.0.2/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:47: attribute 'dialyzer' after function definitions
/usr/local/Cellar/erlang/18.0.2/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:118: attribute 'dialyzer' after function definitions
/usr/local/Cellar/erlang/18.0.2/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:194: attribute 'dialyzer' after function definitions
/usr/local/Cellar/erlang/18.0.2/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:247: attribute 'dialyzer' after function definitions
==> floki
could not compile dependency floki, mix compile failed. You can recompile this dependency with `mix deps.compile floki` or update it with `mix deps.update floki`
```

**Comment by philss** [comment]
@henrik and @licyeus can you provide your Elixir and Erlang versions?

To check Erlang version with brew, use: `brew info erlang | grep "*"`
To check Elixir version, run: `elixir -v`.

**Comment by licyeus** [comment]
```
➜  brew info erlang | grep "*"
/usr/local/Cellar/erlang/17.5 (7398 files, 282M) *
➜  elixir -v
Elixir 1.0.5
```

Interesting that my stacktrace references 18.0.2, but brew states I'm running 17.5. I'm upgrading erlang with homebrew and will let you know after lunch if it works.

**Comment by henrik** [comment]
```
$ brew info erlang | grep "*"
/usr/local/Cellar/erlang/17.5 (7398 files, 283M) *
$ elixir -v
Elixir 1.0.4
```

I'll try to hold off on upgrading things so I can evaluate any backwards-compatibility fix (if that's the issue).

**Comment by philss** [comment]
@licyeus @henrik thank you! I will take a look later today. This seems something related to the Erlang version , but I'm not sure. I tested Floki against Erlang `18.0.2` and `18.0.3`, and it works fine.

@henrik Ok.

**Comment by licyeus** [comment]
Upgrading to erlang 18.0.3 (via `brew upgrade erlang`) fixed the issue. Floki now compiles successfully. @philss, thanks for the heads up on how to check system erlang version.

**Comment by henrik** [comment]
👍 If you bump the version I'm happy to try the latest.

**Comment by philss** [comment]
@henrik great! You can take a look now in the new version `0.4.1` (it's already [published](https://hex.pm/packages/floki)).

My bad, guys. The problem was that I added a file that shouldn't be added to the Hex package. You can't see the file because is not under versioning, but is a file that is generated by the "leex" compiler.
This explain why you were seeing "/usr/local/Cellar/erlang/18.0.2/".

Let me know if you have any issues.

Thanks again for reporting! 

cc @licyeus

**Comment by philss** [comment]
@henrik can you try this new version (0.4.1)?

**Comment by henrik** [comment]
Works! 👍 Thanks so much, Philip!

**Comment by philss** [comment]
@henrik Ok, thanks for testing it!
