### ISSUE TITLE
invalid output type in spec for traverse_and_update/3

### ISSUE THREAD

**Issue by RichMorin** [philss/floki#252]
Although `traverse_and_update/3` seems to work nicely, it breaks `mix dialyzer` for me.
The problem is that the output type (as documented  [here](https://hexdocs.pm/floki/Floki.html#traverse_and_update/3)) is specified as `html_tree`.
It should be specified as (something like) `{html_tree, any}`.

**Comment by RichMorin** [comment]
I think line 391 of https://github.com/philss/floki/blob/master/lib/floki.ex needs to be something like:

         ) :: {html_tree(), traverse_acc()}

**Comment by philss** [comment]
Closed by #255
