### ISSUE TITLE
Add E:nth-last-child(n) and E:nth-last-of-type(n) to supported selectors

### ISSUE THREAD

**Issue by TomMatthews1** [philss/floki#257]
Having these would be a great help towards improving accuracy of selectors.

**Comment by philss** [comment]
@TomMatthews1 thanks for the suggestion! :purple_heart:
This feature is published in version [`0.26.0`](https://github.com/philss/floki/blob/master/CHANGELOG.md#0260---2020-02-17). Let me know if it works for you.
