### ISSUE TITLE
Docs and specs for traverse_and_update are wrong

### ISSUE THREAD

**Issue by josevalim** [philss/floki#285]
The docs say that it will receive an `html_tag` but the callback is also called for doctype/comment/pi nodes. I am not sure if you want to fix the specs/docs or the code. :)

**Comment by philss** [comment]
@josevalim thank you for catching it! 💜 
I think the problem is in the docs, because the callback function needs to handle nodes for doctype/comment/pi in order to be able to change it. So we need to update the docs instead of removing the "feature".

**Comment by josevalim** [comment]
Cool, PR sent here #289.
