### ISSUE TITLE
Potential bug in spec for Floki.children/2

### ISSUE THREAD

**Issue by Devon-Olivier** [philss/floki#296]
## Description

`Floki.children/2` has a spec of

`@spec children(html_tree, Keyword.t()) :: html_tree | nil`

 `html_tree()` is a list: `[html_node()]` . However the [body](https://github.com/philss/floki/blob/8e414cf94b4288128bf087a6034d6e59cfdcf785/lib/floki.ex#L482) of the function seems to be pattern matching on an `html_node()` and not a list. 

Should the correct spec be `@spec children(html_node(), Keyword.t()) :: html_tree() | nil` ?

**Comment by philss** [comment]
Thank you, @Devon-Olivier! :purple_heart: 
It is fixed in https://github.com/philss/floki/commit/4e3626d49abe3bb45c505e92c7d9b8354aeff540
