### ISSUE TITLE
Bad XML causes CaseClauseError

### ISSUE THREAD

**Issue by ubermarcin** [philss/floki#305]
When trying to parse html containing XML processing instructions throws:
 `** (CaseClauseError) no case clause matching:` followed by full document represented as string.

- Using Floki v0.28.0
- Using Elixir v1.10.4
- Using Erlang OTP 21 or 22

 html document: https://gist.github.com/ubermarcin/6854a54f7086718ff19998530024f3fc

 Try:
`Floki.parse_document/1`

Expected behavior: Get parset html tree or at least an informative error on bad XML, don't crash.

**Comment by philss** [comment]
@ubermarcin thank you for opening the issue! :purple_heart: 
I added a PR with the fix. I'm going to merge tomorrow if no issue was found.

**Comment by ubermarcin** [comment]
@philss I'm happy to have contributed to this great project!

Re: Pull request with the fix,
I already tested it with example provided and ran regression tests, everything seems to work fine 👍
