### ISSUE TITLE
HTML tags inside <style> elements get interpreted as children.

### ISSUE THREAD

**Issue by SweetMNM** [philss/floki#339]
## Description

I was not writing any Floki code my self, but actually using [Premailex](https://github.com/danschultzer/premailex).
Premailex was throwing an error because it was not ready to find any children inside style tags other than strings, after some debugging I found out Floki was looking at an html tag in my css and parsed that as a children.

## To Reproduce

- Using Floki v0.30.0
- Using Elixir v1.11.3
- Using Erlang OTP v20.3
- With this code:
  ```elixir
    {:ok, document} = Floki.parse_document("
  <html>
    <style>
      .this-works {
        just: fine;
      }

      // Floki will think the p tag bellow is an actual element
      // Match all <p> tags
      p {
        color: red;
      }
    </style>
  </html>
  ")

  Floki.find(document, "style")
  |> IO.inspect(label: "Floki result")
  ```
Output is:
```
Floki result: [
  {"style", [],
   [
     "\n      .this-works {\n        just: fine;\n      }\n\n      // Floki will think the p tag bellow is an actual element\n      // Match all ",
     {"p", [], [" tags\n      p {\n        color: red;\n      }\n    "]}
   ]}
]
```

## Expected behavior

Floki should ignore html tags inside style tags. I did not check the problem with script tags so it it possible they have the same issue.

## Possible solution
https://github.com/philss/floki/blob/fd88a2836f4dd73d42c0d899d9aae5a132aaa7dc/lib/floki/html_tree.ex#L182
Add a pattern match to that function that matches `"style"` instead of `tag` and manually add a text node of the inner content instead of building a tree for the children of a style tag.

**Comment by gkpacker** [comment]
The bug seems to be on the https://github.com/mochi/mochiweb lib:

```elixir
iex(4)> Floki.HTMLParser.Mochiweb.parse_document("
...(4)> <html>
...(4)>   <style>
...(4)>     .this-works {
...(4)>       just: fine;
...(4)>     }
...(4)>
...(4)>     // Floki will think the p tag bellow is an actual element
...(4)>     // Match all <p> tags
...(4)>     p {
...(4)>       color: red;
...(4)>     }
...(4)>   </style>
...(4)> </html>
...(4)> ")
{:ok,
 [
   {"html", [],
    [
      {"style", [],
       [
         "\n    .this-works {\n      just: fine;\n    }\n\n    // Floki will think the p tag bellow is an actual element\n    // Match all ",
         {"p", [], [" tags\n    p {\n      color: red;\n    }\n  "]}
       ]}
    ]}
 ]}
```

**Comment by philss** [comment]
@SweetMNM thanks for opening the issue, and sorry for the delay! :purple_heart: 

Yeah, this is a bug! It is in the tree construction phase. The place you mentioned is not the best one, because the problem is inside mochiweb's code (under "src/floki_mochi_html.erl"). But I think it works for now. Would you like to give a try?

@gkpacker you are right, thanks for pointing out! :purple_heart:

**Comment by philss** [comment]
@SweetMNM Just another thing: you may want to use Floki with [FastHTML](https://hexdocs.pm/floki/readme.html#alternative-html-parsers). The only downside is that you need a C compiler when installing your dependencies. But this parser gets it right and it's really fast.

**Comment by SweetMNM** [comment]
@gkpacker Thanks!

@philss I didn't know floki had a bundled version of mochiweb that can be modified. I don't mind tackling this on the elixir side of things. Mochiweb just looks like a huge thing to tackle and I am also not very experienced with erlang. So since mochiweb is the default parser and it does not require external dependencies it is probably used by most people. For that reason I think it's fair to "help" mochiweb a bit on the elixir side of things. If that sounds reasonable to you then I don't mind working on that.

Let me know :)

> you may want to use Floki with FastHTML.
I thought about it but traumatized by native dependencies in node I decided to just go along with mochiweb. I might end up switching to it for pure speed reasons though...

**Comment by philss** [comment]
> I thought about it but traumatized by native dependencies in node I decided to just go along with mochiweb. I might end up switching to it for pure speed reasons though...

I know this feeling. I had bad experiences in Ruby with Nokogiri. :sweat_smile: 
I think `fast_html` is much more "simple" because it does not require any dependencies other than the compiler. 

> If that sounds reasonable to you then I don't mind working on that.

@SweetMNM I agree, please go ahead :+1:

**Comment by SweetMNM** [comment]
> I think fast_html is much more "simple" because it does not require any dependencies other than the compiler.

I will give it a try then 😄
