### ISSUE TITLE
Floki.find() doesn't appear to work with html, head, or body elements

### ISSUE THREAD

**Issue by crertel** [philss/floki#345]
## Description

`Floki.find/2` seems unable to select `head`, `body`, or `html` elements.

## To Reproduce

- Using Floki v0.30.1
- Using Elixir v1.11.4
- Using Erlang OTP v23.3.1
- With this code:
``` iex(56)> Floki.parse_document("<html></html>")                                                                                        
{:ok, [{"html", [], []}]}
iex(57)> Floki.parse_document("<html><head></head><body></body></html>")                                                              
{:ok, [{"html", [], [{"head", [], []}, {"body", [], []}]}]}
iex(58)> Floki.parse_document("<html><head></head><body></body></html>") |> Floki.find("body")
[]
iex(58)> Floki.parse_document("<html><head></head><body></body></html>") |> Floki.find("head")
[]
iex(58)> Floki.parse_document("<html><head></head><body></body></html>") |> Floki.find("html")
[]
```

## Expected behavior

I'd expect to see the subtrees for the elements show up.

**Comment by philss** [comment]
@crertel it's because `Floki.parse_document/2` returns a tuple `{:ok, document}`.

Please try this instead:

```elixir
{:ok, doc}  = Floki.parse_document("<html><head></head><body></body></html>")

Floki.find(doc, "body")
```

Or:

```elixir
Floki.parse_document!("<html><head></head><body></body></html>") |> Floki.find("body")
```

See: https://hexdocs.pm/floki/Floki.html#parse_document/2

**Comment by crertel** [comment]
Ah, yep, that does it. Thanks!

I was also trying to use Floki to parse a `<!DOCTYPE NETSCAPE-Bookmark-file-1>` doc, which ended badly.

I'm noticing that the `:root` pseudoselector isn't implemented...any chance we could get it?

**Comment by philss** [comment]
@crertel I think it's possible to implement the `:root` pseudo-selector. Would you mind to open a new feature request?

And about the doctype problem: can you provide an example of the document and the error?
Thanks!

**Comment by crertel** [comment]
Sure, will do!

I don't think the doctype issue is important--Floki did its job the best it's able, it is just that the HTML for Firefox bookmark exports is a colossal mess (lots of missing and non-matching tags, no `head` or `body` tags, etc.).
