### ISSUE TITLE
Not all meta tags are found

### ISSUE THREAD

**Issue by rouven-uncap** [philss/floki#349]
## Description

Parsing a Tweet html, Floki only returns the initial 11 `<meta>` tags. Notice in the document from twitter.com below, several `<script>` and `<link>` tags follow, and then additional `<meta>` tags are present. These are not found by Floki.

## To Reproduce

- Using Floki v0.30.1
- Using Elixir v1.11.2
- Using Erlang OTP 23
- With this code:
```
{:ok, %{body: body}} = HTTPoison.get("https://twitter.com/SpaceX/status/1389672850089418752") 
{:ok, document} = Floki.parse_document(body)
Floki.find(document, "meta")
```
## Expected behavior

All `<meta>` tags should be returned by the query

**Comment by philss** [comment]
@rouven-uncap for what I could see, they are all returned:

![floki-twitter-meta](https://user-images.githubusercontent.com/381213/117149502-a844b080-ad8d-11eb-84eb-3dce1018b923.png)

Maybe Twitter is returning a different result when downloading using `HTTPoison`. I downloaded the file using `curl` and then I opened in my iex. Please try again.

**Comment by rouven-uncap** [comment]
If you look further down below the link and script tags, there are more meta tags below, which are not returned in your screenshot:

![image](https://user-images.githubusercontent.com/82147217/117154121-db059d80-adbb-11eb-91b3-ed38e11ce8d4.png)

**Comment by rouven-uncap** [comment]
You are correct about curl. Maybe those extra meta tags are injected into the DOM via JS after the page is loaded, which completely defeats the purpose of meta tags...
