### ISSUE TITLE
Floki parses badly formed attributes (a[href]) in this case

### ISSUE THREAD

**Issue by RobertDober** [philss/floki#370]
Floki 0.26
Elixir 1.12.3 and 1.13.0-rc.0

## Description
The input `"<a href=\"http://foo.bar.baz/%{foo}\">http://foo.bar.baz/%{foo}</a>"` is not legal HTML (as can be checked [here](https://validator.w3.org/nu/#textarea) e.g.)

nevertheless Floki parses is as correct

## To Reproduce
```elixir
{:ok,
 [
   {"a", [{"href", "\\\"http://foo.bar.baz/%{foo}\\\""}],
    ["http://foo.bar.baz/%{foo}"]}
 ]}

```
## Expected behavior
return `{:error, ....}`

**Comment by philss** [comment]
Hi @RobertDober :wave: 

Today the parsers used by Floki are tolerant to errors, just like the browsers, and they will try their best to parse something from a malformed HTML. This is the default behavior of the majority of HTML parsers out there for historic reasons. That said, I think this is not a bug. But in the future we could have some flag to be "strict" and return error in case of parsing errors.

**Comment by RobertDober** [comment]
I was in stress mode when writing this ticket, and I forget to mention that Floki is really very useful to me for testing in Earmark, so thank you for that :heart: 

 I understand your reasoning that AAMOF Floki should parse as much as possible.
Maybe the docs could be a little bit clearer about that.

I like the `strict` idea which would be great for _my_ usecase, but IIUC you would need to forward this kind of request to the underlying parsers (amazing stuff you are doing with Rust connection BTW)
But, of course I had to write the Issue **before** looking at the code :blush:

Sorry if I was writing this with kind of a tunnel vision.
