### ISSUE TITLE
FunctionClauseError

### ISSUE THREAD

**Issue by mmport80** [philss/floki#40]
I received an error when trying to parse the html of this page. Let me know if you need anything else.

http://theguysociety.com/success/kunal-desai-no-bull-on-how-to-take-over-the-stock-market/?utm_content=buffer4be54&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

** (FunctionClauseError) no function clause matching in Floki.Finder.traverse/4
             lib/floki/finder.ex:33: Floki.Finder.traverse({:pi, "php echo date(\"Y\"); "}, ["  | ", {"a", [{"href", "http://crossatlanticebooks.com"}, {"target", "_blank"}], ["Cross Atlantic E-Books"]}, " , a division therein                        "], %Floki.Selector{attributes: [%Floki.AttributeSelector{attribute: "property", match_type: :equal, value: "og:image"}], classes: [], combinator: nil, id: nil, type: "meta"}, [])
             lib/floki/finder.ex:40: Floki.Finder.traverse/4
             lib/floki/finder.ex:40: Floki.Finder.traverse/4
             lib/floki/finder.ex:44: Floki.Finder.traverse/4
             lib/floki/finder.ex:40: Floki.Finder.traverse/4
             lib/floki/finder.ex:23: Floki.Finder.find/2
      (hue2) lib/hue2/tweet_info_2.ex:263: Hue2.TweetInfo2.get_source_data/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
      (hue2) lib/hue2/tweet_info_2.ex:98: Hue2.TweetInfo2.store/0

**Comment by mmport80** [comment]
Oops, here's what I am looking for: Floki.find("meta[property='og:image']")

**Comment by philss** [comment]
@mmport80 thanks for the report! :)

It is fixed in the latest version, 0.7.1. Pls check that.

**Comment by mmport80** [comment]
fantastic - working great - thanks!
