### ISSUE TITLE
Attributes' names are forced lowercase

### ISSUE THREAD

**Issue by qertoip** [philss/floki#42]
Floki forces attributes' names lowercase. Failing test case:

    defmodule FlokiTest do
      use ExUnit.Case
    
      test "preserves case of attributes names" do
        xml = ~s(<root ID="1"/>)
        [{"root", [{attrName, "1"}], []}] = Floki.find(xml, "root")
        assert(attrName == "ID")
      end    
    end

**Comment by philss** [comment]
@qertoip Thanks for the report!

This is a problem in the parsing step. Unfortunately the parser is under the `mochiweb` code base. I'm working to get a [built-in parser](https://github.com/philss/floki/issues/37) soon.  I will let this issue open until I can solve this.

**Comment by ckruse** [comment]
since HTML is case-insensitive, this is IHMO the right behaviour

**Comment by philss** [comment]
I agree with @ckruse. This is the expected behavior since Floki is not supposed to be fully compatible with XML. Thanks for the report and sorry for the delay, @ckruse.
