### ISSUE TITLE
How to filter out comments?

### ISSUE THREAD

**Issue by ckruse** [philss/floki#44]
Hi,

I'd like to filter out comments, how do I do it? I tried

    Floki.filter_out(doc, :comment)

But that doesn't work.

**Comment by philss** [comment]
Hi @ckruse,

This is actually a bug. It's fixed in this commit 5ec7eda, and I should release a new version with the fix soon. In the meanwhile, please use the github version.

Thanks!

**Comment by ckruse** [comment]
Thank you very much!

**Comment by philss** [comment]
@ckruse This fix is available in the version 0.7.2. Thanks!

**Comment by ckruse** [comment]
Thanks - just released version 0.0.3 of my [microformats2 parser](https://hex.pm/packages/microformats2) depending on that version :-)
