### ISSUE TITLE
Is there a way to replace paragraph tags by newlines in Floki.text()?

### ISSUE THREAD

**Issue by BlackEdder** [philss/floki#452]
I would like to use Floki to cleanup/parse html and output a normal utf8 string. I have been able to do that using

```elixir
html |> Floki.parse_fragment!() |> Floki.text()
```

but would prefer paragraphs `<p>text</p>` to be followed by a newline when calling `Floki.text()`. I did try `Floki.text([sep: "\n"])` but that results in new lines being inserted too readily.

**Comment by philss** [comment]
@BlackEdder have you tried with [`Floki.traverse_and_update/2`](https://hexdocs.pm/floki/Floki.html#traverse_and_update/2)?
