### ISSUE TITLE
Add an optional separator to .text()  

### ISSUE THREAD

**Issue by rochdi** [philss/floki#49]
consider this case:
```Floki.parse("<ul><li>text1</li><li>text2</li><ul>") |> Floki.text ```
returns 
`text1text2 `

If we give the consumer the possibility to add a separator 
```Floki.parse("<ul><li>text1</li><li>text2</li><ul>") |> Floki.text (separator: " ")```
returns 
```text1 text2```

**Comment by rochdi** [comment]
Hi @philss, I have a local branch with this feature implemented and tested.

**Comment by philss** [comment]
@rochdi hi there! This feature is interesting. Can you open a PR with this?
It's important to not affect the result if no separator is passed. Thanks!

**Comment by rochdi** [comment]
@philss getting 403 when trying to push my branch, can you give me access ? or there is another procedure to follow.

**Comment by philss** [comment]
@rochdi It's better to fork and push to your fork. You can do as follow: 

1. Fork:
![fork_button](https://cloud.githubusercontent.com/assets/381213/15513903/fa28b796-21bc-11e6-84a1-05c747e03899.png)

2. After fork, get the git URL from that "Clone or Download" button;
![screen shot 2016-05-24 at 2 31 26 pm](https://cloud.githubusercontent.com/assets/381213/15514006/69589168-21bd-11e6-8153-38753ca386b3.png)

3. Set your local git repo to point to that repo:
```
$ git remote set-url origin git@github.com:rochdi/floki.git
```
4. Push your branch to that repo:
```
$ git push -u origin your-branch
```
5. Open the PR using the Github UI (it will appear in your fork as an option).

**Comment by rochdi** [comment]
@philss thanks and done
Adding a separator will prevent user from losing words, specify if the sentence will go through some NLP

**Comment by philss** [comment]
@rochdi right, thanks! I will take a better look later today.
