### ISSUE TITLE
parentheses not supported in css selector 

### ISSUE THREAD

**Issue by rochdi** [philss/floki#53]
* Example: .test nth-child(2) 
* message: `Unknown token '('. Ignoring.`

**Comment by gmile** [comment]
@rochdi this is a known issue, see "Known issues" section in description of https://github.com/philss/floki/pull/22:

> There is no support for pseudo-selectors;

**Comment by philss** [comment]
Gonna close this one since it's already a known issue, and I don't have plans to add pseudo-selectors right now.

@rochdi feel free to open a more specific issue, like: `Add support for nth-child pseudo-selector`. 

Thanks @gmile and @rochdi !
