### ISSUE TITLE
Empty tag attributes are not parsed correctly

### ISSUE THREAD

**Issue by 1player** [philss/floki#558]
```
iex(4)> Floki.parse_document("<a href></a>")
{:ok, [{"a", [{"href", "href"}], []}]}
```

Floki interprets this example as if it was `<a href="href">` which is of course wrong. I would expect either Floki to represent the empty attribute as an empty string, or to omit it altogether.

**Comment by 1player** [comment]
Does not seem to affect fast_html

**Comment by philss** [comment]
This is a limitation of the default parser, `mochiweb_html`. Please try to use `FastHTML` or `HTML5ever` as the README suggest.

**Comment by 1player** [comment]
That's worth documenting, rather than closing this bug as "completed", no? What's the point of shipping with a broken parser?

**Comment by philss** [comment]
@1player sorry, I don't wanted to sound rude. My point was to point out that this is documented in our README: https://github.com/philss/floki?tab=readme-ov-file#alternative-html-parsers
