### ISSUE TITLE
Floki.attribute shouldn't return a list

### ISSUE THREAD

**Issue by gmile** [philss/floki#56]
Is there a reason why `Floki.attribute` returns a list?

Right now I find myself constantly needing to run `hd` or `List.first` when retrieving attribute's value:

```elixir
~s(<meta property="og:url" name="twitter:url" content="https://example.com">)
|> Floki.parse()
|> Floki.find(~s(meta[property="og:url"]))
|> Floki.attribute("content")
|> hd()
```
Attribute name is always uniqe, so it should be possible to have `hd/1` in `Floki.attribute` itself?

According to the [HTML5 CR, 8.1.2.3 Attributes](https://www.w3.org/TR/html5/syntax.html#attributes-0):

> There must never be two or more attributes on the same start tag whose names are an ASCII case-insensitive match for each other.

**Comment by gmile** [comment]
On the other hand, I think it makes sense. Give there's a list of matches returned by `Floki.find`, `Floki.attribute` will return a flat list of attributes (instead of list of lists containing single attribute's value).

I'm closing this, sorry for misunderstanding.

**Comment by philss** [comment]
Ok, no problem 👍
