### ISSUE TITLE
issues with fetching floki as dependeny

### ISSUE THREAD

**Issue by Levin** [philss/floki#562]
## Description

when running mix deps.get ({:floki, ">= 0.30.0"}) we ran into a timeout
after specifying to {:floki, "==0.36.0"} everything went well

also, the current version on github is still displayed as "0.36.0" but in your git history, you already updated to "0.36.1".

## To Reproduce

- Using Floki v0.36.1
- Using Elixir v1.16.2
- Using Erlang OTP v26.2.4
- With this code:
  ```elixir

mix deps.get
mix.exs holds {:floki, ">= 0.30.0"}

  ```

## Expected behavior

mix should fetch the current version of floki

**Comment by philss** [comment]
I think this is a network problem. Maybe your network or Hex were down. Please try again with the latest version.

**Comment by Levin** [comment]
works with the latest version, thanks ;)
