### ISSUE TITLE
Document type declaration (DOCTYPE) is not parsed

### ISSUE THREAD

**Issue by quentin-bettoum** [philss/floki#578]
Hello,

I've noticed that the DOCTYPE is not parsed.
I did not dig too much into the lib code yet, but it seems that it's supposed to be parsed.

```elixir
iex> "<!DOCTYPE html><html></html>"|> Floki.parse_document!() |> Floki.raw_html() |> dbg()

"<!DOCTYPE html><html></html>" #=> "<!DOCTYPE html><html></html>"
|> Floki.parse_document!() #=> [{"html", [], []}]
|> Floki.raw_html() #=> "<html></html>"

"<html></html>"

```

**Comment by philss** [comment]
This is because the default parser does not keep the doctype. Please try with `html5ever`, as instructed in the README.

```elixir
"<!DOCTYPE html><html></html>"
|> Floki.parse_document!(html_parser: Floki.HTMLParser.Html5ever)
```

**Comment by quentin-bettoum** [comment]
> This is because the default parser does not keep the doctype. Please try with `html5ever`, as instructed in the README.
> 
> ```elixir
> "<!DOCTYPE html><html></html>"
> |> Floki.parse_document!(html_parser: Floki.HTMLParser.Html5ever)
> ```

Thanks, I missed that part of the doc
