### ISSUE TITLE
Floki.find/2 doesn't find ids ending with `?`

### ISSUE THREAD

**Issue by randycoulman** [philss/floki#583]
## Description

I originally thought that this might be a [bug in PhoenixTest](https://github.com/germsvel/phoenix_test/issues/97), but it looks it's actually in Floki.

If I have a form field with an id ending in a `?` character (e.g. `active?`), Floki is unable to find the element. If I remove the `?`, then all is well.

## To Reproduce

(h/t to @germsvel for coming up with a simple example)

- Using Floki v0.36.2
- Using Elixir v1.17.2
- Using Erlang OTP v27.0.1
- With this code:
```elixir
test "floki doesn't accept ? in id" do
      html = """
      <div id="hello?">
        Hello world
      </div>
      """

      text =
        html
        |> Floki.parse_fragment!()
        |> Floki.find("#hello?")
        |> Floki.text()

      assert text =~ "Hello world"
    end 
```

## Expected behavior

I'd expect Floki to be able to find the element.

**Comment by ypconstante** [comment]
`#hello?` isn't a valid selector, both Chrome and Firefox raise an error with it

```
> document.querySelector("#hello?")
VM74:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#hello?' is not a valid selector.
```

You'll need to use [Floki.get_by_id/2](https://hexdocs.pm/floki/Floki.html#get_by_id/2) or `|> Floki.find("[id='hello?']")`

**Comment by randycoulman** [comment]
Wow, interesting! Thanks for taking a look @ypconstante! I did search for whether that was a valid DOM id, and it seems to be from what I can tell. But if it doesn't work as a selector, that makes things difficult.

I'll close this.
