### ISSUE TITLE
parse_document! returns a 4-element tuple for doctype when using html5ever parser

### ISSUE THREAD

**Issue by vkryukov** [philss/floki#598]
## Description

When parsing a document with a doctype using `Floki.HTMLParser.Html5ever`, the first element of the 
resulting html tree is a 4-element tuple `{:doctype, "html", "", ""}`. It breaks the (apparent) contract that each HTML node is represented by a tuple like `{tag_name, attributes, children_nodes}`, and breaks some downstream code (e.g., https://github.com/keepcosmos/readability/issues/65).

## To Reproduce

- Using Floki v0.36.3
- Using Elixir v1.17.3
- Using Erlang OTP v27
- With this code:
 ```elixir
html = """
<!doctype html>
<html>
<body>
  <section id="content">
    <p class="headline">Floki</p>
    <span class="headline">Enables search using CSS selectors</span>
    <a href="https://github.com/philss/floki">Github page</a>
    <span data-model="user">philss</span>
  </section>
  <a href="https://hex.pm/packages/floki">Hex package</a>
</body>
</html>
"""

IO.inspect(Floki.parse_document!(html, html_parser: Floki.HTMLParser.Html5ever))
 ```

returns
```
[
  {:doctype, "html", "", ""},
  {"html", [],
   [
     {"head", [], []},
     {"body", [],
      [
        "\n",
        "  ",
        {"section", [{"id", "content"}],
         [
           "\n",
           "    ",
           {"p", [{"class", "headline"}], ["Floki"]},
           "\n",
           "    ",
           {"span", [{"class", "headline"}],
            ["Enables search using CSS selectors"]},
           "\n",
           "    ",
           {"a", [{"href", "https://github.com/philss/floki"}], ["Github page"]},
           "\n",
           "    ",
           {"span", [{"data-model", "user"}], ["philss"]},
           "\n",
           "  "
         ]},
        "\n",
        "  ",
        {"a", [{"href", "https://hex.pm/packages/floki"}], ["Hex package"]},
        "\n",
        "\n",
        "\n"
      ]}
   ]}
]
```

## Expected behavior

We expect that each HTML tree produced by `parse_document` and friends to consist only of 3-element tuples like `{tag_name, attributes, children_nodes}`.

**Comment by philss** [comment]
Hi @vkryukov, thanks for open the issue.
The specs says that [`Floki.parse_document/2`](https://hexdocs.pm/floki/Floki.HTMLParser.html#c:parse_document/2) returns a `Floki.html_tree()`, which is just a list of `[html_node()]`. An `html_node()` can be also a `:doctype` declaration, as in https://hexdocs.pm/floki/Floki.html#t:html_node/0

So my understanding is that _readability_ needs to adjust its code to handle/ignore the doctype declaration.

**Comment by vkryukov** [comment]
Ah, you are write of course! I didn't notice that `html_doctype()`. Then everything is good, I will close this (and I've already patched it in `readability`).
