### ISSUE TITLE
Add attribute equals selector

### ISSUE THREAD

**Issue by philss** [philss/floki#6]
The "attribute equals" selector is useful when one wants to search elements by the value of some attribute, like data attributes or "schema" properties.

Check the [jQuery documentation](https://api.jquery.com/attribute-equals-selector/) for more details.

**Comment by philss** [comment]
Closed by #12 :fireworks:

**Comment by philss** [comment]
@nelsonr the new version is available in hex.pm with this new feature. Thanks a lot!

**Comment by nelsonr** [comment]
@philss happy to contribute! :)
