### ISSUE TITLE
Using `filter_out` with attribute selector like "div[class]"

### ISSUE THREAD

**Issue by marick** [philss/floki#61]
Suppose I want to filter out all divs that have a particular attribute. I can't see how to do that with `filter_out`. 

Consider this HTML. It has one div with a `class` and one without:

``` elixir
html = "<body> <div class=\"has\">one</div>  <div>two</div> </body>"
```

I want to find all the divs without a `class`. I expected this to work, but it does not:

``` elixir
iex(44)> Floki.filter_out(html, "div[class]")
{"body", [], [{"div", [{"class", "has"}], ["one"]}, {"div", [], ["two"]}]}
```

More precisely, I want to work with a list produced by `find`, so a closer approximation to my real code would be this:

``` elixir
iex(40)> Floki.find(html, "div") |> Floki.filter_out("div[class]")
[{"div", [{"class", "has"}], ["one"]}, {"div", [], ["two"]}]
```

Note that filtering _in_ the div with `class` works (using `find`):

``` elixir
iex(42)> Floki.find(html, "div") |> Floki.find("div[class]")
[{"div", [{"class", "has"}], ["one"]}]
```

So does filtering out all the divs, regardless of their attributes:

``` elixir
iex(45)> Floki.find(html, "div") |> Floki.filter_out("div")
[]
```

Am I doing something wrong?

**Comment by marick** [comment]
Update: It appears from https://github.com/philss/floki/blob/master/lib/floki/filter_out.ex#L15 that the second argument to `filter_out` is not intended to be a CSS selector, but just a tag name (or pseudo-name like `:comment`)

**Comment by justgage** [comment]
I personally think that this should be a selector. `Floki.find` works this way. Plus it would just make it much more useful.

**Comment by philss** [comment]
@marick thanks for the report! You are correct, the implementation expects only a "type" (tag name) or pseudo-name. This opens two possible actions: improve docs to make that more explicit or accept an actual selector and work like `Floki.find/2` do.

I agree with @justgage that implementing the selector is more useful. But I'm not sure if we can reuse the internals of `Floki.find/2` or implement a new algo here.

I'm gonna think about this. Feel free to suggest or open a PR. :)

**Comment by StanBright** [comment]
Yeah, I expected that `filter_out` would work with selectors as `find` does.

Away from that, `Floki` works flawlessly for me at the moment :)

**Comment by philss** [comment]
@marick Sorry for the delay. This problem is fixed in version `0.13.0` released today. The signature remains the same, but now you can use more complex selectors (the same that are accepted by `Floki.find`).

cc/ @StanBright 

Thank you!

**Comment by philss** [comment]
Update: please use version `0.13.1` that has two bug fixes.

**Comment by marick** [comment]
Thank *you*. I [know](https://github.com/marick/Midje/issues) how medium-scale open source projects produce a good amount of work, but nowhere near the [egoboo](https://en.wikipedia.org/wiki/Egoboo) that big projects do.
