### ISSUE TITLE
IO.puts bloat

### ISSUE THREAD

**Issue by teamon** [philss/floki#63]
ref https://github.com/philss/floki/blob/ba3b1e3587e7fff90c38df1da7ede09f86d8fcf3/lib/floki/selector_parser.ex#L62-L63

How about 

```ex
Logger.debug("[floki] Unknown token #{inspect unknown}. Ignoring.")
```

?

**Comment by justgage** [comment]
I'm not a maintainer but I'm curious how this is different or less "bloat"

**Comment by teamon** [comment]
@justgage If you set the logger level to info (or warn, or error) it won't be displayed.

**Comment by justgage** [comment]
Ah, makes sense

**Comment by philss** [comment]
@teamon I agree with you. But I think this message should be a `warn` instead of `debug`. This is because the user may want to know that misspelled selectors are affecting the results of a given search.

I added this commit 5d4c0a9 that fixes the issue. I gonna release it soon.

Thank you! :)

**Comment by illia-danko** [comment]
@philss Hello back to this discussion and for sure indirectly connected to the topic itself, but is it possible to change logging level for the library only? I'm seeking for something like:
```
# in my app config/config.exs

config :floki, :logger, level: :error
```
Which could work from both develop and prod environments.

Any advice or workaround is welcome :)

**Comment by philss** [comment]
hey @illia-danko, I think you can use the `:compile_time_purge_matching` config from Logger. I recently added a note to the README.md about that: https://github.com/philss/floki#suppressing-log-messages
I honestly didn't test it though. Please let me know if this works for you. 

PS: I should release a new version soon, which is going to decrease the majority of messages to `:debug`. See https://github.com/philss/floki/pull/488

**Comment by illia-danko** [comment]
@philss I do not use log lever lower than info for development as well, and after a new 0.35.0 release I can set global logger level to info and the messages are disappear. Thank you
