### ISSUE TITLE
A deep version of Floki.text/1?

### ISSUE THREAD

**Issue by citizenparker** [philss/floki#7]
First off, I'm a big fan of this library - I really like the approach it's taking.

I'm using it to simplify my assertions in Phoenix Controller tests, and I find that a version of [Floki.text/1](http://hexdocs.pm/floki/Floki.html#text/1) that returned text deeply would be super useful for me, letting me write tests that are agnostic to styling choices in the template. In the example in this method's documentation, I'm proposing something that would work like so:

```elixir
iex> Floki.text("<div><span>something else</span>hello world</div>", deep: true)
"something elsehello world"
```

Thoughts?

**Comment by philss** [comment]
@citizenparker Great to know that you like and is using Floki! :smiley: 

I like your idea. I was in doubt when I added the `Floki.text/1`, if it should work with this "deep" behavior by default. I choose to not follow this path, but I don't remember why.

We can make the `Floki.text/1` work with the "deep" strategy by default. It can also have an option to make it work as it is today. The option could be like you mentioned, but setted to `true` by default.

Examples:

```elixir
iex> Floki.text("<div><span>something else</span>hello world</div>")
"something elsehello world"

iex> Floki.text("<div><span>something else</span>hello world</div>", deep: false)
"hello world"
```

What do you think?

**Comment by philss** [comment]
@citizenparker following your suggestion, I changed the behavior of `Floki.text/1` to perform a deep search and I added an option (`deep`) to disable the deep search if needed.

Please check [the docs](http://hexdocs.pm/floki/0.2.0/Floki.html#text/2) for more details.
You need to update your projects to use the version `0.2.0` of Floki.

Thanks for the suggestion!
