### ISSUE TITLE
Finding article Tag

### ISSUE THREAD

**Issue by dc0d** [philss/floki#74]
Hi,

`Floki.find(html, "article")` returns nothing despite the fact the html does contain an `article` tag. No other selectors find that tag too.

Thanks;

**Comment by philss** [comment]
@dc0d can you provide a HTML sample?

**Comment by dc0d** [comment]
My apologies (Elixir Noob); I was working on an RSS. I was wrong and making a mistake. After `article_elem = Floki.find(html, "article") |> Floki.text()` then I was using `inspect` on the result which gives a binary representation (like `<<67, 164, ...>>`) instead of the text ([sample link](http://www.gameblog.fr/news/63744-concours-gagnez-un-pc-gamer-portable-et-des-figurines-star-w) - I do not know French!).

I expected inspect on a string would just return that string.

This issue should get closed.

Thanks for the fast reply again!

**Comment by philss** [comment]
@dc0d no worries, thank you!
I'm closing this now.
