### ISSUE TITLE
Find with ":" token

### ISSUE THREAD

**Issue by Jesterovskiy** [philss/floki#78]
I use Floki to parse XML. When I need to find "media:thumbnail" it returns me empty list.

Example:
iex(2)> Floki.find(response.body, "item") |> List.first
{"item", [],
 [{"title", [], ["Test"]},
  {"description", [], ["test"]},
  {"media:thumbnail",
   [{"url", "test-url"}], []},]}
iex(3)> Floki.find(Floki.find(response.body, "item") |> List.first, "media:thumbnail")
[]

Maybe I use Floki wrong? Thank you for help)

**Comment by philss** [comment]
Hi @Jesterovskiy 

You need to replace the `:` by `|` (a pipe) in the selector. [Here is the spec](https://www.w3.org/TR/selectors/#typenmsp).

```elixir
Floki.find(Floki.find(response.body, "item") |> List.first, "media|thumbnail")
```

I'm gonna close this one. Please reopen if this didn't work for you.
