### ISSUE TITLE
Plus in find not work as expected

### ISSUE THREAD

**Issue by Eiji7** [philss/floki#79]
For this code:
```html
<span>1</span>&nbsp;<a>2</a>
```
I run:
```elixir
Floki.find(html, "span + a")
```
Expected results:
```elixir
[{"a", [], ["2"]}]
```
Actual results:
```elixir
[]
```
**Note**:
With this html:
```html
<span>1</span> <a>2</a>
```
and this:
```html
<span>1</span><a>2</a>
```
find method works as expected.

So problem is that `Floki` interprets `&nbsp;` (text node) as normal node. So next element (for Floki) after `span` element is text node instead of `a` element.

**Note2**:
As a workaround I tried:
```elixir
Floki.find(html, "span + * + a") # any element between span and link
```
but I got:
```elixir
** (MatchError) no match of right hand side value: " "
                lib/floki/finder.ex:137: Floki.Finder.traverse_sibling/3
                lib/floki/finder.ex:69: Floki.Finder.traverse/4
                lib/floki/finder.ex:73: Floki.Finder.traverse/4
                lib/floki/finder.ex:47: Floki.Finder.find_selectors/2
```

**Comment by philss** [comment]
@Eiji7 Good catch! I think this problem extends not only for  the sibling selector (">"). It should have the same problem for general sibling ("~") and the "nth-child" pseudo class selector.

I'm looking into fix this soon. Thank you for the report!
