### ISSUE TITLE
How to find the previous sibling element?

### ISSUE THREAD

**Issue by baoxiehao** [philss/floki#89]
Example first:

```html
<div class="panel-heading">FUN &amp; COOL</div>
<div class="panel-body">
```

What I want to achieve is that when I have found "panel-body" already, I need to fetch something (like heading text) from "panel-heading".
What I know is the selector "A + B" to find the next sibling element, but I didn't find the previous sibling selector in Floki. 

The following code will not work(markup is above mentioned "panel-body"):

```elixir
Floki.find(markup, ":before") |> Floki.text
```

Does any one tell me how to do it right? Much thanks~

**Comment by philss** [comment]
Hi @baoxiehao!

I think there is no way to do that easily today. And worst: there is no "stable" specification for this kind of selector in the specs of CSS level 4.
The closest thing I found is the [`:has()` pseudo-selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has), which is a little bit complex to implement IMO.

One idea is to implement the `:previous-sibling` pseudo-selector. This would be easier to implement and use, but would diverge a little bit from CSS (which doesn't have the feature today).

If we go with that, would be nice to add a `floki` sufix to that (`:floki-previous-sibling`) until the feature be available in the CSS 4 specs.

What do you think?
If you want to give a try, the first place to look is [here](https://github.com/philss/floki/blob/master/lib/floki/finder.ex#L97-L109).

**Comment by baoxiehao** [comment]
Since the spec is not available now, it's quite reasonable there is no easy way to reach what I had imaged.

So for now, I think the easiest way is to find the "panel-heading" first, and from that using "A + B" to find "panel-page" element, and lastly combine the related parts to get what I want.

Thanks for your detailed reply @philss ^_^
