### ISSUE TITLE
Add support for `Floki` and / or jQuery special selectors.

### ISSUE THREAD

**Issue by Eiji7** [philss/floki#92]
Add `Floki` and / or jQuery special selectors. More info at [Category: Selectors at jQuery docs](https://api.jquery.com/category/selectors/).
Examples:
```css
:floki-has-text("     a text       ")
:floki-has-trimmed-text("a text")
:jquery-empty
```
Add more `Floki` special selectors suggestions as a comments for this issue.
**Note**: I split my comment and add its half as current issue on @philss request at #82 issue.

**Comment by philss** [comment]
I will close this one and open individual issues for each selector we want. Thank you.
